version: "3.9"

services:
  mcp-doc-retriever:
    container_name: mcp-doc-retriever
    build: .
    ports:
      - "8001:8000"
    environment:
      # ArangoDB connection settings (example, adjust as needed)
      ARANGO_HOST: http://arangodb:8529
      ARANGO_USER: root
      ARANGO_PASSWORD: ${ARANGO_PASSWORD:-mcp_password} # Or use a .env file

    volumes:
      - download_data:/app/downloads
    depends_on:
      - arangodb
      - redis
    restart: unless-stopped

  arangodb:
    container_name: mcp-arangodb
    image: arangodb:latest  # Or specify a version
    ports:
      - "8529:8529"
    environment:
      ARANGO_ROOT_PASSWORD: ${ARANGO_PASSWORD:-mcp_password}  # Use same password or separate
    volumes:
      - arango_data:/var/lib/arangodb3

  redis:
    container_name: mcp-redis
    image: redis:latest  # Or specify a version
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

volumes:
  download_data:
  arango_data:
  redis_data: